from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

FOLDER_EXPORTS = BASE_DIR / "EXPORTS"
FOLDER_INPUTS = BASE_DIR / "INPUTS FOLDER"
FOLDER_DATA = BASE_DIR / "DATABASE"
FOLDER_CONFIG = BASE_DIR / "CONFIG"
FOLDER_HISTORY = BASE_DIR / "HISTORY"

GRAPH_DIR = FOLDER_EXPORTS / "graficas"
TABLE_DIR = FOLDER_EXPORTS / "tablas"
HTML_GRAPH_DIR = FOLDER_EXPORTS / "graficas_html"

folders = {
    "BASE_DIR": BASE_DIR,
    "FOLDER_EXPORTS": FOLDER_EXPORTS,
    "FOLDER_INPUTS": FOLDER_INPUTS,
    "FOLDER_DATA": FOLDER_DATA,
    "FOLDER_CONFIG": FOLDER_CONFIG,
    "FOLDER_HISTORY": FOLDER_HISTORY,
    "GRAPH_DIR": GRAPH_DIR,
    "TABLE_DIR": TABLE_DIR,
    "HTML_GRAPH_DIR": HTML_GRAPH_DIR,
}